name: Simon Wu
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
theme: minima
title: Simon's Site
description: A place to write about things I'm interested in.
author: Simon Wu